---
#
- name: Restart server
  shell: reboot
  when: restart

- name: Wait for server to come up
  local_action: wait_for host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %} port=22 delay=30
  when: restart