---
# ----------------------------------------------------------------------------
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------
#
#  ------------------------- Created by -------------------------------------- 
#
#  Name: Gabriel Popa
#  Company: Iello-Dev srl
#  Country: Romania 
#  Email: contact@iello.ro
#
#
# ----------------------------------------------------------------------------
#
- name: Delete the MQ directory
  file: path={{ MQDirectory }} state=absent
  ignore_errors: true
  when: fromScratch

- name: Delete symlink
  file: path={{ MQHome }} state=absent
  ignore_errors: true
  when: fromScratch

- name: Delete startup script
  file: path=/etc/init.d/{{ MQService }} state=absent
  ignore_errors: true
  when: fromScratch

- name: Unarchive mq archive
  unarchive: src={{ MQArchive }} dest={{ MQTarget }} owner={{ WSO2Owner }} group={{ WSO2Group }}
  when: fromScratch

- name: Create necessary symbolic link
  file: src={{ MQDirectory }} dest={{ MQHome }} owner={{ WSO2Owner }} group={{ WSO2Group }} state=link force=yes
  when: fromScratch

- name: Create necessary symbolic link
  file: src={{ MQDirectory }}/bin/linux-x86-64/activemq dest=/etc/init.d/{{ MQService }} owner={{ WSO2Owner }} group={{ WSO2Group }} state=link force=yes
  when: fromScratch

- name: Change daemon file 
  template: src=daemon/activemq.j2 dest={{ MQHome }}/bin/linux-x86-64/activemq owner={{ WSO2Owner }} group={{ WSO2Group }} mode=0777

- name: Ensure MQ service is enabled for startup
  service: name={{ MQService }} enabled=yes state=started

- name: Change installation directory ownership
  file: path={{ MQDirectory }} owner={{ WSO2Owner }} group={{ WSO2Group }} state=directory recurse=yes

- name: Verify machine hostname to be correctly set
  hostname: name={{ inventory_hostname }}

- lineinfile: dest=/etc/hosts regexp='.*{{ inventory_hostname }}$' insertafter="^127\.0\.0\.1(.*)localhost" line="{{ ansible_eth0['ipv4']['address'] }} {{ inventory_hostname }}" state=present

- name: Restart server
  shell: reboot
  when: restart

- name: Wait for server to come up
  local_action: wait_for host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %} port=22 delay=30
  when: restart
#
#
# EOF: profitbricks-esb-dev/roles/mq/tasks/main.yml