---
# ----------------------------------------------------------------------------
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------
#
#  ------------------------- Created by -------------------------------------- 
#
#  Name: Gabriel Popa
#  Company: Iello-Dev srl
#  Country: Romania 
#  Email: contact@iello.ro
#
#
# ----------------------------------------------------------------------------
#
WSO2CarbonVersion: '4.9.0'
Alias: 'esb'
Offset: 0

# Installation directory
WSO2Archive: '{{ Nickname }}{{ Alias }}-{{ WSO2CarbonVersion }}.zip'
WSO2CarbonDirectory: '{{ WSO2CarbonTarget }}{{ Nickname }}{{ Alias }}-{{ WSO2CarbonVersion }}'

# carbon.xml
HostName: '{{ CarbonServicesAlias }}{{ Alias }}.{{ Environment }}{{ Domain }}'
MgtHostName: '{{ Alias }}.{{ Environment }}{{ Domain }}'
DeploymentSynchronizer: 'true'
AutoCommit: "{% if type == 'manager' %}true{% else %}false{% endif %}"
StatisticsReporterDisabled: 'false'

# registry.xml
RegistryReadOnly: "{% if type == 'manager' %}false{% else %}true{% endif %}"

# axis2/axis2.xml
Clustering: 'true'
MembershipScheme: 'wka'
ClusterDomain: '{{ Alias }}.cluster.{{ Environment }}{{ Domain }}'
LocalMemberPort: "{{ ClusterPortPrefix }}0{{ node }}"
#
#
# EOF: profitbricks-esb-dev/roles/esb/vars/vars.yml