---
# ----------------------------------------------------------------------------
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------
#
#  ------------------------- Created by -------------------------------------- 
#
#  Name: Gabriel Popa
#  Company: Iello-Dev srl
#  Country: Romania 
#  Email: contact@iello.ro
#
#
# ----------------------------------------------------------------------------
#
- name: Remove MariaDB repository (1)
  apt_repository: repo='deb http://mirror.vpsfree.cz/mariadb/repo/5.5/ubuntu trusty main' state=absent update_cache=yes
  ignore_errors: true

- name: Remove MariaDB repository (2)
  apt_repository: repo='deb http://mirror3.layerjet.com/mariadb/repo/5.5/ubuntu trusty main' state=absent update_cache=yes
  ignore_errors: true

- name: Stop mysql server if started
  service: name=mysql state=stopped
  ignore_errors: true

- name: Stop MySQL resident services
  shell: ps -ef | grep -iv grep | grep {{ MySQLOwner }} | awk '{ print $2 }' | sudo xargs kill -9
  ignore_errors: true

- name: Ensure MariaDB Galera Cluster packages are removed
  apt: name={{ item }} state=absent force=yes purge=yes
  with_items:
    - libmariadbclient18 
    - libmysqlclient18 
    - mariadb-common
    - mariadb-galera-server
    - mariadb-client
    - galera-3
    - lsof
    - rsync
    - python-mysqldb
    - python-dev
    - mysql-server
    - mysql-client 
    - mysql-common
    - mysql*
    - galera*
  ignore_errors: true

# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

- name: Remove configuration file
  file: path=/etc/mysql/conf.d/cluster.cnf state=absent force=yes

- name: Delete MySQL lib directory
  shell: rm -rf /var/lib/mysql/*
  ignore_errors: true

- name: Delete MySQL installed binaries
  shell: rm /usr/bin/mysql*
  ignore_errors: true

- name: Delete MySQL installed binaries
  shell: rm -rf /var/log/mysql
  ignore_errors: true

- user: name={{ MySQLOwner }} state=absent remove=yes
- group: name={{ MySQLGroup }} state=absent
#
#
# EOF: profitbricks-esb-dev/roles/maria/tasks/1.clean.yml